travis:
  secure:
    BINSTAR_TOKEN: ZHMQtvnwifzDN+Dl32VaS3fXMv8uOwFITQVn/T3KgsF59F8WfEYVbjzjQ+duFTg06APKHxAp0bCJk1d2imV9MGBc3uWKg+Jiahl0avhKnsxQ3a6HhRT4FYynhS7Pg5MUb8aCbc73HYsPr2Hql69yOo0XUAbUaWgBnwiTDmPbjsvW/1dvmmMBAYNBuSXAVRBJeDTFXYm1dXU1USQ5WJaBAe+ng6OpYJAxzz6nmLQajSGN+AdI9RBZvw6/mgjSKtYknapw7d+IXepVgnHXsf7CVOfQheuDuOEUwUomeUL3KKO4uR95Y8qymh18BQSjmcDwsoTtohWu2lHPDV2r5vyuvYQsR2vpMVWSXTD+Hi6FZc+RywGEKq1wyZJ57e60vjp43+73uzd+lU7udTP7n4XXMdyXdoiXmthXnsuIhZfFZqDTgK9T+lROxsaOMh2joZKJufSrRCCGbR4tQagwo8yCMA/ZrGnONFpgMmS6WJs1o2TH5RiCEjCejohizTQzMqwyLyoYDpMm/Eda+GYoM3p5L6ucTUkAgeg688sEUPdJ4AidT2npKYCNaOu4ygbW0vQ8aA1EcyYqkQQ5Y8NYEFsn+uAUbAOM8lZbdZQdZIj8ZfXuvOyGhuCoHudS0FgEhG5xkvYGjFdyXjvUFC5PUVVX9DoFjc38BWdcd/t7lskyyfo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure